export default{
  NEXT_STEP: 'NEXT_STEP',
  RADIO_CHECK: 'RADIO_CHECK',
  START: 'START',
  ADD_POINTS: 'ADD_POINTS',
  RESTART: 'RESTART',
  ANSWER: 'ANSWER',
  AGE_CHANGE: 'AGE_CHANGE',
  REGION_CHANGE: 'REGION_CHANGE'
}
